### ISSUE TITLE
Support for theme-color in Chrome 39 for Android

### ISSUE THREAD

**Issue by minsoopark** [ridi/ridicorp.github.io#1]
롤리팝 안드로이드용 크롬이 meta 태그 theme-color 속성, 192x192 favicon을 지원합니다.

우리 페이지에도 넣으면 좋을 것 같아요.

![theme-color-ss-9950fd13a0c52b32b6bd580309d55a6b](https://cloud.githubusercontent.com/assets/1253530/6390190/899c0034-bded-11e4-9487-c67661b21e1b.png)

[링크](http://updates.html5rocks.com/2014/11/Support-for-theme-color-in-Chrome-39-for-Android) 참고

**Comment by jaeminbae** [comment]
테스트해봤는데 주소입력창까지 색깔이 바뀌어 부담스러운 느낌이었습니다.
서점의 경우는 특히 GNB와 색깔이 겹쳐서 보기가 좋지 않았습니다 (...)
theme-color는 기본 컬러를 쓰고, favicon을 좀 예쁘게 바꾸는 방향으로 하기로 하였습니다.
